# Implementation of ML Algorithms in Python 3.6.5

## 1. Back Propagation

In [25]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
%matplotlib inline

In [26]:
# Function importing Dataset
def importdata():
    balance_data = pd.read_csv(
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data',
    sep= ',', header = None)
     
    # Printing the dataswet shape
    print ("Dataset Lenght: ", len(balance_data))
    print ("Dataset Shape: ", balance_data.shape)
     
    # Printing the dataset obseravtions
    print ("Dataset: ",balance_data.head())
    return balance_data

In [27]:
data=importdata()

Dataset Lenght:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5


In [28]:
# Function to split the dataset
def splitdataset(balance_data):
 
    # Seperating the target variable
    X = balance_data.values[:, 1:5]
    Y = balance_data.values[:, 0]
 
    # Spliting the dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.3, random_state = 100)
     
    return X, Y, X_train, X_test, y_train, y_test

In [29]:
X, Y, X_train, X_test, y_train, y_test = splitdataset(data)

In [108]:
# Function to perform training with giniIndex.
def train_using_BP(X_train, X_test, y_train):
 
    # Creating the classifier object
    BP = MLPClassifier(activation='relu',solver='sgd',hidden_layer_sizes=(100,100,100,100,100,100,100,100,100,100,100),random_state=1)
 
    # Performing training
    BP.fit(X_train, y_train)
    return BP

In [109]:
BP = train_using_BP(X_train, X_test, y_train)

In [110]:
# Function to make predictions
def prediction(X_test, clf_object):
 
    # Predicton on test with giniIndex
    y_pred = clf_object.predict(X_test)
    print("Predicted values:")
    print(y_pred)
    return y_pred

In [114]:
y_pred = prediction(X_test, BP)

print("\n \n Test values: \n", y_test)

Predicted values:
['L' 'L' 'R' 'L' 'R' 'B' 'R' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L'
 'B' 'L' 'L' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'L'
 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'R' 'B' 'R' 'R' 'R' 'L' 'R' 'B'
 'R' 'L' 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'B' 'B' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'L' 'B' 'L' 'B' 'R' 'L' 'R' 'R' 'R'
 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L'
 'L' 'B' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R'
 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'R' 'L' 'R' 'B' 'L' 'R' 'R'
 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'L' 'R' 'B' 'L' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'R' 'R']

 
 Test values: 
 ['L' 'L' 'R' 'L' 'R' 'B' 'R' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'L'
 'B' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 

In [112]:
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
     
    print("Confusion Matrix: \n",
        confusion_matrix(y_test, y_pred))
     
    print ("Accuracy : \n",
    accuracy_score(y_test,y_pred)*100)
     
    print("Report : \n",
    classification_report(y_test, y_pred))

In [113]:
cal_accuracy(y_test, y_pred)

Confusion Matrix: 
 [[12  0  1]
 [ 1 83  1]
 [ 0  1 89]]
Accuracy : 
 97.87234042553192
Report : 
              precision    recall  f1-score   support

          B       0.92      0.92      0.92        13
          L       0.99      0.98      0.98        85
          R       0.98      0.99      0.98        90

avg / total       0.98      0.98      0.98       188

